"""Evaluation metrics for Corpus2Skill.

Lexical metrics (F1, BLEU, ROUGE), semantic metric (BERTScore-F1) and
LLM-judge metrics:

  * ``judge_factuality``           — answer vs gold (essential-info coverage)
  * ``judge_context_recall``       — retrieved context vs gold
  * ``judge_faithfulness_grounded`` — answer claims supported by retrieved context
  * ``judge_answer_relevance``     — does the answer address the question
  * ``judge_context_precision``    — fraction of retrieved context that is on-topic

Plus an aggregate helper ``hallucination_rate`` (faithfulness_grounded < 0.6).

The factuality / context-recall prompts follow the WixQA evaluation protocol
(arXiv:2505.08643). The faithfulness / answer-relevance / context-precision
prompts are RAGAS-style 1-5 LLM judges.
"""

from __future__ import annotations

import collections
import json
import os
import re
import sys
import time


def _tokenize(text: str) -> list[str]:
    """Simple whitespace + punctuation tokenizer."""
    return re.findall(r"\w+", text.lower())


def compute_f1(prediction: str, reference: str) -> float:
    """Token-level F1 score."""
    pred_tokens = _tokenize(prediction)
    ref_tokens = _tokenize(reference)
    if not pred_tokens or not ref_tokens:
        return 0.0

    pred_counter = collections.Counter(pred_tokens)
    ref_counter = collections.Counter(ref_tokens)
    common = sum((pred_counter & ref_counter).values())

    if common == 0:
        return 0.0
    precision = common / len(pred_tokens)
    recall = common / len(ref_tokens)
    return 2 * precision * recall / (precision + recall)


def compute_bleu(prediction: str, reference: str) -> float:
    """Sentence-level BLEU with smoothing."""
    from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
    pred_tokens = _tokenize(prediction)
    ref_tokens = _tokenize(reference)
    if not pred_tokens or not ref_tokens:
        return 0.0
    smoothing = SmoothingFunction().method1
    return sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smoothing)


def compute_rouge(prediction: str, reference: str) -> dict[str, float]:
    """ROUGE-1 and ROUGE-2 F-measure."""
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2"], use_stemmer=True)
    scores = scorer.score(reference, prediction)
    return {
        "rouge1": scores["rouge1"].fmeasure,
        "rouge2": scores["rouge2"].fmeasure,
    }


# ---------------------------------------------------------------------------
# LLM-judge metrics
# ---------------------------------------------------------------------------

FACTUALITY_PROMPT = """You are a Factual Alignment Expert. Your job is to evaluate how well an AI response includes the essential information from a ground truth answer (GT answer) according to a given user query.

Note that the Ground Truth (GT Answer), is the "Correct" answer generated by an expert, and was created to evaluate the model, and is NOT part of the AI response or the context.

TASK DESCRIPTION:
You will be presented with three elements: a question, a GT answer, and an AI response. Determine how well the AI response includes the essential information from the GT answer that helps to solve the user's query. In case of any additional or extra information present in the AI response, only make sure it's not preventing the user from solving his query.

EVALUATION CRITERIA:
5: Complete Match - All essential information from GT answer appears in AI response, providing complete solution to the query
4: Strong Match - Most essential information is present, with only minor details missing that don't impact the solution significantly
3: Partial Match - Core information is present but missing some important details that would help better solve the query
2: Limited Match - Only basic or partial information present, missing several essential elements needed for the solution
1: Poor Match - Missing most essential information or contains incorrect information that could mislead the user

INSTRUCTIONS:
1. Read the question carefully and analyze the ground truth answer to identify all key information elements that help solve the query
2. Compare the AI response (candidate answer) against the ground truth, focusing on presence of important information
3. Evaluate the completeness and accuracy of the information transfer
4. Assign a rating (1-5) based on how well important information is preserved
5. Provide a brief explanation focusing on factuality

## Question
{question}

## GT Answer
{gold_answer}

## AI Response
{predicted_answer}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


CONTEXT_RECALL_PROMPT = """You are a Context Evaluation Expert. Your job is to assess how well a retrieved context contains the essential information present in a ground truth answer (GT answer).

TASK DESCRIPTION:
You will be presented with three pieces of information: a user query, its ground truth answer, and a retrieved context (that will be used to create an AI response from). Determine how well the essential information from the GT answer appears in the retrieved context. Additional information in the retrieved context should not affect the scoring.

EVALUATION CRITERIA:
5: Complete Match - All essential information from the GT answer is present in the retrieved context. The context fully enables answering the user's question.
4: Strong Match - All essential information is present, but some minor details are missing. The context still effectively answers the user's question.
3: Partial Match - Most essential information is present, but some important details are missing. The context partially answers the user's question.
2: Weak Match - Only basic or limited essential information is present. The context provides insufficient information to properly answer the user's question.
1: No Match - Essential information is missing or incorrect. The context cannot be used to answer the user's question.

INSTRUCTIONS:
1. Read the question to understand what the user asks for
2. Break down the GT answer into essential information (key facts, main concepts, direct answers)
3. Check if these information pieces appear in the retrieved context
4. Focus only on finding the ground truth information in the context - ignore extra information
5. Assign a rating (1-5) based on information coverage and relevance

## Question
{question}

## GT Answer
{gold_answer}

## Retrieved Context
{context}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


def _llm_judge(prompt: str, client, model: str, max_retries: int = 5) -> dict:
    """Call LLM judge, parse JSON response, normalize score to 0-1."""
    for attempt in range(max_retries + 1):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=300,
                messages=[{"role": "user", "content": prompt}],
            )
            text = response.content[0].text.strip()
            start = text.index("{")
            end = text.rindex("}") + 1
            result = json.loads(text[start:end])
            raw_score = result.get("score", 0)
            return {
                "raw_score": raw_score,
                "score_01": round(raw_score / 5.0, 2),
                "explanation": result.get("explanation", ""),
            }
        except Exception as e:
            if ("429" in str(e) or "rate_limit" in str(e)) and attempt < max_retries:
                delay = 30 * (2 ** attempt)
                time.sleep(delay)
                continue
            return {"raw_score": 0, "score_01": 0.0, "explanation": f"Judge error: {e}"}


def judge_factuality(question: str, predicted: str, gold: str, client, model: str) -> dict:
    """Judge how well the predicted answer captures the gold answer's essential info."""
    prompt = FACTUALITY_PROMPT.format(
        question=question,
        gold_answer=gold[:4000],
        predicted_answer=predicted[:4000],
    )
    return _llm_judge(prompt, client, model)


def judge_context_recall(question: str, gold: str, context: str, client, model: str) -> dict:
    """Judge how well the retrieved context covers the gold answer."""
    prompt = CONTEXT_RECALL_PROMPT.format(
        question=question,
        gold_answer=gold[:4000],
        context=context[:8000],
    )
    return _llm_judge(prompt, client, model)


# ---------------------------------------------------------------------------
# BERTScore (semantic F1) — embedding-based similarity to the gold answer.
# ---------------------------------------------------------------------------

_BERTSCORE_MODEL = os.environ.get("BERTSCORE_MODEL", "roberta-large")
_BERTSCORE_LANG = os.environ.get("BERTSCORE_LANG", "en")
_bertscorer = None  # lazy-init singleton


def _get_bertscorer():
    global _bertscorer
    if _bertscorer is None:
        from bert_score import BERTScorer  # type: ignore

        device = os.environ.get("BERTSCORE_DEVICE")
        kwargs = dict(
            model_type=_BERTSCORE_MODEL,
            lang=_BERTSCORE_LANG,
            rescale_with_baseline=False,
            idf=False,
        )
        if device:
            kwargs["device"] = device
        _bertscorer = BERTScorer(**kwargs)
    return _bertscorer


def compute_bertscore_f1(prediction: str, reference: str) -> float:
    """Single-pair BERTScore-F1. Returns 0.0 on empty input / model error."""
    if not prediction or not reference:
        return 0.0
    try:
        scorer = _get_bertscorer()
        _, _, F1 = scorer.score([prediction], [reference])
        return float(F1[0])
    except Exception as e:
        print(f"  [bertscore] error: {e}", file=sys.stderr)
        return 0.0


def compute_bertscore_batch(
    predictions: list[str],
    references: list[str],
) -> list[float]:
    """Batched BERTScore for efficiency. Returns F1 per pair."""
    if not predictions:
        return []
    try:
        scorer = _get_bertscorer()
        preds = [p or "(empty)" for p in predictions]
        refs = [r or "(empty)" for r in references]
        _, _, F1 = scorer.score(preds, refs)
        return [float(x) for x in F1]
    except Exception as e:
        print(f"  [bertscore-batch] error: {e}", file=sys.stderr)
        return [0.0] * len(predictions)


# ---------------------------------------------------------------------------
# LLM-as-judge: Faithfulness (context-grounded)
# ---------------------------------------------------------------------------

FAITHFULNESS_GROUNDED_PROMPT = """You are a Faithfulness Evaluation Expert. Your job is to determine whether the claims in an AI-generated answer are supported by the retrieved context that was given to the model.

This is different from comparing the answer to a gold answer. We are specifically asking: does every claim in the AI response have explicit support in the retrieved context? Unsupported claims indicate the model is using training-data knowledge to fill gaps or fabricating information ("hallucination").

EVALUATION CRITERIA (1-5 scale):
5: Fully Grounded — Every claim in the AI response is directly supported by the retrieved context. No unsupported assertions.
4: Mostly Grounded — Almost all claims are supported; one or two minor details may not be explicitly in the context but are reasonable extrapolations.
3: Partially Grounded — Roughly half of the claims are supported by the context; the rest appear to come from training knowledge or are unsupported elaborations.
2: Weakly Grounded — Only a minority of claims are supported. Most of the answer comes from outside the retrieved context.
1: Not Grounded — Essentially none of the claims are supported by the retrieved context. The answer ignores the context or fabricates details.

INSTRUCTIONS:
1. Read the question to understand the user's intent.
2. Identify the discrete claims / factual statements in the AI response.
3. For each claim, check whether it can be verified from the retrieved context (verbatim or by clear paraphrase).
4. Penalize for unsupported claims, fabricated specifics (numbers, names, URLs), and citations not present in the context.
5. Do NOT penalize for missing information — that's a recall problem, not a faithfulness problem.

## Question
{question}

## Retrieved Context
{context}

## AI Response
{predicted_answer}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason naming any unsupported claims"}}"""


def judge_faithfulness_grounded(
    question: str,
    predicted: str,
    context: str,
    client,
    model: str,
) -> dict:
    """Judge whether the claims in ``predicted`` are supported by ``context``."""
    prompt = FAITHFULNESS_GROUNDED_PROMPT.format(
        question=question,
        context=context[:12000],
        predicted_answer=predicted[:4000],
    )
    return _llm_judge(prompt, client, model)


# ---------------------------------------------------------------------------
# LLM-as-judge: Answer Relevance
# ---------------------------------------------------------------------------

ANSWER_RELEVANCE_PROMPT = """You are an Answer Relevance Evaluation Expert. Your job is to assess whether an AI response actually addresses the user's question — independent of whether the answer is factually correct.

A response can be perfectly grounded in the retrieved context and still be irrelevant (e.g., it answers a related but different question, drowns the user in tangential background, or fails to commit to an answer).

EVALUATION CRITERIA (1-5 scale):
5: Directly On-Point — The response directly answers the question with no unnecessary digression.
4: Mostly On-Point — The response answers the question; some extra context is included but doesn't dilute the answer.
3: Partially Relevant — The response addresses part of the question but misses other aspects, or pads heavily with tangential content.
2: Mostly Off-Topic — The response touches on the topic but does not actually answer what was asked.
1: Off-Topic / Non-Answer — The response does not answer the question (e.g., refusal, ignores the question, asks a counter-question).

INSTRUCTIONS:
1. Parse the question to identify what is being asked (intent, specifics requested).
2. Read the AI response and check whether it directly addresses those specifics.
3. Penalize for padding, tangents, or non-committal hedging that does not deliver an answer.
4. Ignore factual correctness for this metric — only judge whether the question is addressed.

## Question
{question}

## AI Response
{predicted_answer}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


def judge_answer_relevance(
    question: str,
    predicted: str,
    client,
    model: str,
) -> dict:
    """Judge whether ``predicted`` actually answers ``question``."""
    prompt = ANSWER_RELEVANCE_PROMPT.format(
        question=question,
        predicted_answer=predicted[:4000],
    )
    return _llm_judge(prompt, client, model)


# ---------------------------------------------------------------------------
# LLM-as-judge: Context Precision (holistic)
# ---------------------------------------------------------------------------

CONTEXT_PRECISION_PROMPT = """You are a Context Precision Evaluation Expert. Your job is to estimate what fraction of the retrieved context is relevant to answering the user's question.

This complements Context Recall (which asks whether the answer is *present* in the context). Context Precision asks whether the retrieved context is *focused* — high precision means the retrieved documents are about the question; low precision means the retriever brought back a lot of noise that the model has to ignore.

EVALUATION CRITERIA (1-5 scale):
5: Highly Precise — Almost all of the retrieved context is directly relevant to the question.
4: Mostly Precise — The majority is relevant; some unrelated paragraphs are present but minor.
3: Mixed — Roughly half of the retrieved content is relevant; the rest is noise / tangential.
2: Mostly Noisy — Only a minority of the retrieved content is relevant to the question.
1: Off-Target — Essentially none of the retrieved context is relevant.

INSTRUCTIONS:
1. Parse the question to identify the topic and what kind of evidence would help answer it.
2. Read the retrieved context and estimate what fraction of it is directly useful for answering this question.
3. Do NOT penalize for missing content — that's Context Recall. Penalize for irrelevant content occupying the model's context window.
4. Ignore Markdown structure / formatting noise — focus on substantive content.

## Question
{question}

## Retrieved Context
{context}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


def judge_context_precision(
    question: str,
    context: str,
    client,
    model: str,
) -> dict:
    """Judge what fraction of ``context`` is relevant to ``question``."""
    prompt = CONTEXT_PRECISION_PROMPT.format(
        question=question,
        context=context[:12000],
    )
    return _llm_judge(prompt, client, model)


# ---------------------------------------------------------------------------
# Aggregate helper: hallucination rate (no extra LLM call).
# ---------------------------------------------------------------------------

def hallucination_rate(
    per_q: list[dict],
    threshold: float = 0.6,
    key: str = "faithfulness_grounded",
) -> float:
    """Fraction of queries where ``key`` < ``threshold``.

    Defaults to faithfulness_grounded < 0.6 (raw 1-5 score ≤ 3), matching
    common production thresholds (target ≥ 0.8 / 4-of-5). Queries with a
    None / missing score are skipped.
    """
    valid = [q for q in per_q if "error_detail" not in q]
    scored = [q for q in valid if isinstance(q.get(key), (int, float))]
    if not scored:
        return 0.0
    halluc = sum(1 for q in scored if q[key] < threshold)
    return halluc / len(scored)
